title : Form.io Help
kramdown:
  input: GFM
permalink: pretty
baseUrl: http://formio.github.io/help.form.io/
exclude:
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
collections:
  books:
    output: true
    permalink: /:path/
  chapters:
    output: false
  paragraphs:
    output: false
